version: 1
accounts:
  - name: matt
    coins: ["1000mattcoin", "100000000chipino"]
  - name: matt2
    coins: ["500mattcoin"]
validator:
  name: matt
  staked: "100000000chipino"
genesis:
  chain_id: "chipinochain"
  app_state:
    staking:
      params:
        bond_denom: "chipino"

